### ISSUE TITLE
i.actor.add is not a function ?

### ISSUE THREAD

**Issue by tahma** [paradoxxxzero/gnome-shell-system-monitor-applet#255]
a lot of users have this problem
on debian stable and gnome 3.4.2
good to know that the v24 is working

**Comment by jhaiduce** [comment]
Same problem on RHEL 7 (although this is expected since it was already reported for CentOS 7)

**Comment by brunetton** [comment]
## Workaround found !

I found the breaking commit, using [git bisect] (http://git-scm.com/docs/git-bisect). So to make extension works with Debian Wheezy, follow the [manual install] (https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet#manual-install) and reset git repo to the *last good knonw commit* :

    cd [your_git_repos]/gnome-shell-system-monitor-applet
    git reset --hard cc86a2825185a

Then *restart gnome-shell* (<kbd>Alt</kbd> + <kbd>F2</kbd>, <kbd>r</kbd>, <kbd>Enter</kbd>)

**Comment by jhaiduce** [comment]
The workaround suggested by brunetton works for me on RHEL 7.

**Comment by ezerusso** [comment]
It did work for me too, at Centos 7 x64. Thanks!
